# Generated by Django 2.0.13 on 2019-04-22 01:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cycle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 4, 22, 1, 40, 11, 11537, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FIR', 'Primer Año'), ('SEC', 'Segundo Año'), ('THI', 'Tercer Año'), ('FOU', 'Cuarto Año'), ('FIF', 'Quinto Año'), ('SIX', 'Sexto Año'), ('NIN', 'Septimo Año')], default='FIR', max_length=3)),
                ('division', models.CharField(choices=[('A', 'Division A'), ('B', 'Division B'), ('C', 'Division C'), ('D', 'Division D'), ('E', 'Division E')], default='A', max_length=1)),
                ('shift', models.CharField(choices=[('MS', 'Turno mañana'), ('ES', 'Turno tarde'), ('NS', 'Turno noche')], default='MS', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CourseHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerLibrary.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Preceptor',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 4, 22, 1, 40, 11, 14325, tzinfo=utc))),
                ('presence', models.NullBooleanField()),
                ('preceptor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerLibrary.Preceptor')),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_subject', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='subjects', to='managerLibrary.Subject'),
        ),
        migrations.AddField(
            model_name='presence',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerLibrary.Student'),
        ),
        migrations.AddField(
            model_name='phone',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='managerLibrary.Student'),
        ),
        migrations.AddField(
            model_name='grades',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerLibrary.Professor'),
        ),
        migrations.AddField(
            model_name='grades',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerLibrary.Student'),
        ),
        migrations.AddField(
            model_name='grades',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerLibrary.Subject'),
        ),
        migrations.AddField(
            model_name='coursehistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseHistory', to='managerLibrary.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('year', 'division', 'shift')},
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='managerLibrary.Category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='managerLibrary.Student'),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='id_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerLibrary.Course'),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerLibrary.Subject'),
        ),
    ]
